site_name: csvtk - CSV/TSV Toolkit
pages:
- Home: index.md
- Download: download.md
- Usage: usage.md
- Tutorial: tutorial.md
theme: mkdocs

repo_url: https://github.com/shenwei356/csvtk
site_description: csvtk - CSV/TSV toolkit
site_author: shenwei356
google_analytics: ['UA-28948626-9', 'blog.shenwei.me/csvtk']
